### ISSUE TITLE
Plex Sync All Run: Error

### ISSUE THREAD

**Issue by Skol-Tyr** [japanesemediamanager/ShokoServer-WebUI#100]
Error that appears after hitting Plex Sync All Run: 

Message : 
Network Error : / plex/sync/all 404: Not Found

![chrome_2017-06-29_18-55-42](https://user-images.githubusercontent.com/8317275/27748943-3a43248c-5d86-11e7-88cc-df7b3879eca6.png)

**Comment by AreFinstad** [comment]
not when trying to run this "Plex Sync All" command, while it does get this error in the webui it does not enter anything in the Shoko Server Logs either. so no errors on that front.

**Comment by hidden4003** [comment]
Which server version are you using?
