### ISSUE TITLE
Add this as a sub-module to be automatically updated in JMMServer

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoServer-WebUI#50]

**Comment by bigretromike** [comment]
Currently this is optional ;-) as there is even fake index, but yeah eventualy we could do that or just put it inside installer ;-)

**Comment by ElementalCrisis** [comment]
Eventually it will be included but its not possible to make the Web UI a sub-module. These are just the build files and the user would have to install and run Node.JS. The Web UI does have its own auto-updater so once you have any version you'll be able to update to the latest.

**Comment by bigretromike** [comment]
Also we could (me) add function that install webui if youvwant to use it anyway as currently its more as addon that stand-alone app, later it will change ;-) 

On September 15, 2016 10:46:03 PM GMT+02:00, ElementalCrisis <notifications@github.com> wrote:
>Eventually it will be included but its not possible to make the Web UI
>a sub-module. These are just the build files and the user would have to
>install and run Node.JS. The Web UI does have its own auto-updater so
>once you have any version you'll be able to update to the latest. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver-webui/issues/50#issuecomment-247450467

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hidden4003** [comment]
Not possible as release needs to be built, same as jmm server needs to ne compiled. Probably should be a button in jmm that downloads latest release of webui, command is already there as webui uses it for auto update.

**Comment by ElementalCrisis** [comment]
Well we can include 1.0.0 in future releases of JMM Server which should negate this all together,

**Comment by bigretromike** [comment]
And for ex. Add auto update webui at jmmserver start ;-)
