### ISSUE TITLE
Backup/Import settings

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoServer-WebUI#71]
Both work correct now
GET `/api/config/export` return full body of proper settings.json but don't read settings.json - it would be great to be able to download it thru webui or have it in alike textbox that you could copy
POST `/api/config/import` - it would be great to have ability to have same textbox as export and be able to past it there also you could tweak settings by hand this way while pasting it.
Having it formated in that textbox as proper json would be even better but normal text is great for start.

**Comment by hidden4003** [comment]
Added to 0.3.2-dev4

**Comment by hidden4003** [comment]
@bigretromike  sending empty string to server resulted in "OK" response and wiped my settings 😢 
you want a new issue in server for that ?

**Comment by bigretromike** [comment]
would love to do some work there 👍 also don't hesitate and assign me with it !

**Comment by bigretromike** [comment]
@hidden4003 I saw there there was a commit related with this one, https://github.com/japanesemediamanager/ShokoServer/commit/12d50990eef290f31a8bcdb3610b4609589dd7bb did this resolve the problem ? (and because of that you didn't post the issue on server tracker )

**Comment by bigretromike** [comment]
https://github.com/japanesemediamanager/ShokoServer/issues/618 this one have been fix'd;
Tested

**Comment by hidden4003** [comment]
I didn't post issue because I was testing on 3.7.0.6 and had strong suspicion that it was already fixed in master.

**Comment by bigretromike** [comment]
also, try to use proper api for setting single settings as you could overwrite something with not complete config;
https://github.com/japanesemediamanager/ShokoServer/commit/2be6e1be0151eccc12e431f4ef002f860efdeb61
`/api/config/get` args: setting
`/api/config/set` args: setting, value
