### ISSUE TITLE
Removing deprecated api cals

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoServer-WebUI#73]
WebUI probably didn't use much of those that get deprecated but in case I just wanted to ping you that some of them are old and been replaced with new ones and in few next update those deprecated (they are marked in few ways) will be removed from api.

Also you should be happy that there have been added a lot of parameters that can be pass to api and resolve in big performance boost and webui also could benefit from it by using async ask page of data

```limit``` number of items to return
```offset``` starting number of item from list
```offset + limit``` give you paging but you already had that on logs
```level``` you can control on how many levels of object you can get ex. api/filter will return you all filters, with all groups attach to them and so on.. so the minimal usage is ```leve=1```, default the value is ```0``` and this result in full tree
Those are probably the most important 

Nothing except filters/series/ep/file was touched so probably only few that webui use.

The api/version call was also changed a bit so it also return module version and webui channel/version ;-)

**Comment by hidden4003** [comment]
API version I fixed, rest of those seem to work fine.

**Comment by bigretromike** [comment]
Great news ! Thanks 

On November 17, 2016 9:33:38 PM GMT+01:00, hidden4003 <notifications@github.com> wrote:
>API version I fixed, rest of those seem to work fine.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/ShokoServer-WebUI/issues/73#issuecomment-261361406

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
