### ISSUE TITLE
Error 404 on localhost:8111 with ShokoServer 3.7 beta

### ISSUE THREAD

**Issue by SubaruSumeragi** [japanesemediamanager/ShokoServer-WebUI#74]
I have an error 404 on localhost:8111.

I downloaded and extracted ShokoServer-WebUI in "JMMServer install directory"/webui and I deleted index.html and restarted JMM Server.

There is other operations to see the webUI ?

**Comment by bigretromike** [comment]
Probably current webui is not uptodate with jmm/shoko api 

On November 12, 2016 11:24:45 AM GMT+01:00, SubaruSumeragi <notifications@github.com> wrote:
>I have an error 404 on localhost:8111.
>
>I downloaded and extracted ShokoServer-WebUI in "JMMServer install
>directory"/webui and I deleted index.html and restarted JMM Server.
>
>There is other operations to see the webUI ? 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/ShokoServer-WebUI/issues/74

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
This have been fix'd by @hidden4003 with decc6cddb7a894900d60267f17f7939ad87a559a

**Comment by SubaruSumeragi** [comment]
No change with the current beta of ShokoServer, I need to wait the next beta of the server to test this Web UI ?

I just need to extract the master of ShokoServer-WebUI in "C:\Program Files (x86)\JMM\JMM Server\webui" ?

**Comment by bigretromike** [comment]
you extract shokoserver-webui to webui/ so there are files like index.html inside webui and not directory shokoserver-webui.
or you could issue a api call to install it automatically - but thats more work than download and extract.

Remember to download proper zip [THIS ONE](https://github.com/japanesemediamanager/ShokoServer-WebUI/releases/download/0.3.0-dev3/latest.zip)

**Comment by bigretromike** [comment]
also this need newest shoko-server 3.7.0.x that has no installer (if I recall) 
current newest from daily builds is [THIS ONE](https://ci.appveyor.com/api/buildjobs/yfg8se9poeyns3t3/artifacts/JMMServer%2Fjmmserver.zip)

**Comment by bigretromike** [comment]
Also as I missed part with "I deleted index.html" you don't delete index.html as its overwritten from webui.zip 
You should have those files inside webui/ folder:
```
dist/
index.ejs
index.html
```

**Comment by bigretromike** [comment]
@SubaruSumeragi did you manage to install it and run without problem?

**Comment by SubaruSumeragi** [comment]
Now I see a message "Error: Not found!(WebUI 0.3.0-dev3)"

My filesystem : 
![fenetre](https://cloud.githubusercontent.com/assets/4798290/20337536/f9002346-abd1-11e6-81f4-dbd79af4fedd.PNG)

My browser : 
![webui](https://cloud.githubusercontent.com/assets/4798290/20337543/03b81604-abd2-11e6-9bb7-2edb6adfc6f5.PNG)

**Comment by ElementalCrisis** [comment]
@bigretromike linked you to the wrong file, delete everything in the Web UI folder and replace it with this. 

https://github.com/japanesemediamanager/ShokoServer-WebUI/releases/download/0.3.0-dev3/latest.zip

**Comment by SubaruSumeragi** [comment]
Same problem with this one

**Comment by bigretromike** [comment]
@ElementalCrisis check the link - its the same...

**Comment by bigretromike** [comment]
@SubaruSumeragi to be sure please delete everything in webui/ folder and extract only the zip i provided you with. so your folder have only index.ejs index.html and folder named dist. So the app done use any 'debugging' files/folders.

also check if you are running proper JMM/Shoko version.

**Comment by ElementalCrisis** [comment]
Ah yeah you're right, I clicked the one for Server, my bad. :)

**Comment by bigretromike** [comment]
```Error: Not Found``` on login screen mean that there is a version conflict between JMM/Shoko and WebUi 
It looks like that you use OLDER version of jmm/shoko that the master or daily build.

type ```http://127.0.0.1:8111/JMMServerKodi/GetVersion``` in your browser and past the results

**Comment by SubaruSumeragi** [comment]
@bigretromike I done that and yes I'm running a proper Shoko version (the one provided in one of your previous messages)

**Comment by bigretromike** [comment]
ok, just run that url in browser and past results

**Comment by SubaruSumeragi** [comment]
@bigretromike HTTP 503
![503](https://cloud.githubusercontent.com/assets/4798290/20338199/cf7779bc-abd5-11e6-8fd7-deb5c836ba68.PNG)

**Comment by bigretromike** [comment]
That is good output - which means that we not using any broken version (or really old build)

try now 
```http://127.0.0.1:8111/JMMServerKodi/GetVersion.xml```

**Comment by SubaruSumeragi** [comment]
I will test that (it's 8:34AM and I'm gong to work ;) ) this evening

**Comment by bigretromike** [comment]
yeah, if you get anything other than 
```<Response Code="200" Message="3.7.0.904"/>``` 
for example error 503 then its ```netsh``` error or other problem

**Comment by SubaruSumeragi** [comment]
@bigretromike error 503

**Comment by bigretromike** [comment]
@SubaruSumeragi then there is a problem with netsh uacl 
The biggest expert as He had same problem and resolve it is @da3dsoul 
Also anything @da3dsoul will write should be in FAQ related to this issue @ElementalCrisis right ?
I remamber he removed everything from netsh related with jmm and readded it via hand or installer.
Lets wait and see

**Comment by da3dsoul** [comment]
Huh I don't have the power to reopen this issue. Odd. Well whatever. @ElementalCrisis I thought you already added this to the FAQ, but I guess not. Anyway use the bat file I will be linking shortly as admin, and then run Shoko Server as admin once. If it still doesn't work, look in the logs (which are in ProgramData now), right after debug settings to log for an error. (And post it of course)

**Comment by ElementalCrisis** [comment]
I have the bat file but this is a common issue if you're not using the installer, not a bug. I'll add a section to the FAQ for Web UI with the info.

**Comment by da3dsoul** [comment]
https://www.dropbox.com/s/rjuot6xbdyhq0o0/Remove%20JMMS%20from%20urlacl.bat?dl=0

**Comment by da3dsoul** [comment]
Dropbox is being stupid, hopefully that link works

**Comment by bigretromike** [comment]
link don't work at my end ;-) if the issue was common you would pin point to the proper link some time ago.  Its little bug also as there is a code if I recall correctly to make those calls inside shoko when running as admin so running as admin should fix that but it doesn't because there are faulty lines inside netsh that dont want to get overwritten. imo

**Comment by bigretromike** [comment]
@da3dsoul maybe rename file on dropbox as Remove_JMMS_from_urlacl.bat to avoid space hell ;-)

**Comment by da3dsoul** [comment]
https://dl.dropboxusercontent.com/u/31454410/RemoveJMMSfromurlacl.bat

**Comment by bigretromike** [comment]
that one works!

**Comment by SubaruSumeragi** [comment]
Now I have "<Response Code="200" Message="3.7.0.0"/>" for http://127.0.0.1:8111/JMMServerKodi/GetVersion.xml

But I always have "Error: Not found!(WebUI 0.3.0-dev3)" (T_T) (even after extracting the content of ShokoServer-WebUI-0.3.0-dev3.zip\ShokoServer-WebUI-0.3.0-dev3 in webui/)

**Comment by da3dsoul** [comment]
Are there any errors in your JMM log, specifically right after debug settings to log

**Comment by SubaruSumeragi** [comment]
Ah it's OK now may be it's was my browser's cache ^^

**Comment by bigretromike** [comment]
We are glad you resolve the problem.
