### ISSUE TITLE
Recent Files Only Showing Error

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/ShokoServer-WebUI#79]
![image](https://cloud.githubusercontent.com/assets/9443295/21560052/0b286e18-ce0d-11e6-8231-0dc2e64b2aa7.png)

The Recent Files section shows only the error status even though the files were imported successfully.

**Comment by hidden4003** [comment]
fixed in https://github.com/japanesemediamanager/ShokoServer-WebUI/commit/4f3ddd87327ef98b27792604059a8e5ad853c314
