### ISSUE TITLE
Notification Improvements

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/ShokoServer-WebUI#84]
Our current notifications are very basic, instead we should look into adapting a style similar to this style.

![image](https://cloud.githubusercontent.com/assets/9443295/22366004/43223186-e42f-11e6-8a8c-6742f7ad575f.png)

http://www.jqueryscript.net/other/Growl-Style-Message-Toaster-Plugin-For-jQuery-notify.html

When there is a new notification, it will slide in from the right at which the point the user can manually close it or let it fade away after X seconds with X being a user input. For situations where there might be multiple notifications at once or in short succession, we can show 3-5 and then have them start stacking on each other. We do have the global notifications button at the top which updates in realtime showing the user how many new notifcations there are, similar to how the Workers show how many tasks remain. 

Down the line we could even add a report center that further expands on notifications.

**Comment by hidden4003** [comment]
Added notification styles.
